### ISSUE TITLE
Update Vagrant Python

### ISSUE THREAD

**Issue by catalinpreda** [madalinoprea/django-sales-event#2]
Vagrant Python to be updated to the version that Sales Events is using.

**Comment by madalinoprea** [comment]
I've changed Vagrant base image to Ubuntu 11.04 which comes with python 2.7.1 by default. 

In your case, you'll have to destroy current vm and restart everything It will be smooth...

``` bash
cd [where you did the checkout]
git pull
vagrant destroy
vagrant up
```

Then go to: http://localhost:8080/ (Apache will serve the site)
